import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import API from '../utils/api'

function QuickComplaint() {
  const navigate = useNavigate()
  const [form, setForm] = useState({
    name: '',
    address: '',
    date: new Date().toLocaleDateString('en-IN'),
    situation: ''
  })
  const [letter, setLetter] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const handleGenerate = async (e) => {
    e.preventDefault()
    setLoading(true)
    setError('')
    setLetter('')
    try {
      const res = await API.post('/complaint/generate', form)
      setLetter(res.data.letter)
    } catch (err) {
      setError('Failed to generate complaint. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  const handleDownloadPDF = () => {
    const printWindow = window.open('', '_blank')
    printWindow.document.write(`
      <html>
        <head>
          <title>Complaint Letter - LexOS</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 60px; line-height: 1.8; font-size: 14px; }
            h2 { text-align: center; margin-bottom: 40px; }
            pre { white-space: pre-wrap; font-family: Arial, sans-serif; }
            .footer { margin-top: 40px; font-size: 11px; color: #999; text-align: center; }
          </style>
        </head>
        <body>
          <h2>Complaint Letter</h2>
          <pre>${letter}</pre>
          <div class="footer">Generated by LexOS — AI Legal Assistant</div>
        </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.print()
  }

  return (
    <div style={styles.container}>
      <div style={styles.header}>
        <div style={styles.headerLeft}>
          <button style={styles.backBtn} onClick={() => navigate('/dashboard')}>← Back</button>
          <h1 style={styles.logo}>LexOS</h1>
        </div>
        <span style={styles.pageTitle}>📝 QuickComplaint</span>
      </div>

      <div style={styles.content}>
        <div style={styles.topRow}>
          <div>
            <h2 style={styles.heading}>Draft a Complaint Letter</h2>
            <p style={styles.sub}>Describe your situation — AI drafts a formal complaint instantly</p>
          </div>
        </div>

        <div style={styles.twoCol}>
          {/* Form */}
          <div style={styles.formCard}>
            <h3 style={styles.formTitle}>Your Details</h3>
            <form onSubmit={handleGenerate}>
              <label style={styles.label}>Full Name</label>
              <input
                style={styles.input}
                type="text"
                placeholder="Your full name"
                value={form.name}
                onChange={e => setForm({...form, name: e.target.value})}
                required
              />

              <label style={styles.label}>Address</label>
              <input
                style={styles.input}
                type="text"
                placeholder="Your address"
                value={form.address}
                onChange={e => setForm({...form, address: e.target.value})}
                required
              />

              <label style={styles.label}>Date</label>
              <input
                style={styles.input}
                type="text"
                value={form.date}
                onChange={e => setForm({...form, date: e.target.value})}
                required
              />

              <label style={styles.label}>Describe Your Situation</label>
              <textarea
                style={{...styles.input, height: '140px', resize: 'vertical'}}
                placeholder="Explain what happened in detail. E.g. My landlord refused to return security deposit of Rs 50,000 after 3 months of vacating..."
                value={form.situation}
                onChange={e => setForm({...form, situation: e.target.value})}
                required
              />

              {error && <div style={styles.error}>{error}</div>}

              <button
                style={{...styles.submitBtn, opacity: loading ? 0.7 : 1}}
                type="submit"
                disabled={loading}
              >
                {loading ? '⏳ Generating...' : '✨ Generate Complaint'}
              </button>
            </form>
          </div>

          {/* Output */}
          <div style={styles.outputCard}>
            <div style={styles.outputHeader}>
              <h3 style={styles.formTitle}>Generated Letter</h3>
              {letter && (
                <button style={styles.downloadBtn} onClick={handleDownloadPDF}>
                  ⬇️ Download PDF
                </button>
              )}
            </div>

            {!letter && !loading && (
              <div style={styles.emptyOutput}>
                <div style={{fontSize: '40px', marginBottom: '12px'}}>📄</div>
                <p style={styles.emptyText}>Your complaint letter will appear here</p>
                <p style={styles.emptySub}>Fill in the form and click Generate</p>
              </div>
            )}

            {loading && (
              <div style={styles.emptyOutput}>
                <div style={{fontSize: '40px', marginBottom: '12px'}}>⏳</div>
                <p style={styles.emptyText}>AI is drafting your complaint...</p>
                <p style={styles.emptySub}>This takes about 5-10 seconds</p>
              </div>
            )}

            {letter && (
              <pre style={styles.letterText}>{letter}</pre>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}

const styles = {
  container: { minHeight: '100vh', background: '#0a0b0f' },
  header: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '20px 32px', borderBottom: '1px solid rgba(255,255,255,0.07)',
    background: '#111217'
  },
  headerLeft: { display: 'flex', alignItems: 'center', gap: '16px' },
  backBtn: {
    background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)',
    color: '#888898', padding: '8px 14px', borderRadius: '8px', fontSize: '13px'
  },
  logo: {
    fontSize: '22px', fontWeight: '800',
    background: 'linear-gradient(135deg, #E8E8EE, #4F6EF7)',
    WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent'
  },
  pageTitle: { color: '#E8E8EE', fontSize: '15px', fontWeight: '600' },
  content: { padding: '40px 32px' },
  topRow: { marginBottom: '32px' },
  heading: { fontSize: '26px', fontWeight: '700', color: '#E8E8EE', marginBottom: '6px' },
  sub: { color: '#888898', fontSize: '14px' },
  twoCol: {
    display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px'
  },
  formCard: {
    background: '#111217', border: '1px solid rgba(255,255,255,0.07)',
    borderRadius: '16px', padding: '28px'
  },
  formTitle: { fontSize: '16px', fontWeight: '700', color: '#E8E8EE', marginBottom: '16px' },
  label: { display: 'block', fontSize: '12px', color: '#888898', marginBottom: '6px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.05em' },
  input: {
    width: '100%', background: '#181a21',
    border: '1px solid rgba(255,255,255,0.07)',
    borderRadius: '10px', padding: '12px 16px',
    color: '#E8E8EE', fontSize: '14px',
    marginBottom: '16px', display: 'block',
    fontFamily: 'inherit'
  },
  submitBtn: {
    width: '100%', background: '#4F6EF7', color: '#fff',
    padding: '13px', borderRadius: '10px',
    fontSize: '15px', fontWeight: '600', marginTop: '4px'
  },
  error: {
    background: 'rgba(228,88,88,0.1)', border: '1px solid rgba(228,88,88,0.2)',
    color: '#E45858', padding: '10px 14px', borderRadius: '8px',
    fontSize: '13px', marginBottom: '16px'
  },
  outputCard: {
    background: '#111217', border: '1px solid rgba(255,255,255,0.07)',
    borderRadius: '16px', padding: '28px', display: 'flex',
    flexDirection: 'column'
  },
  outputHeader: {
    display: 'flex', justifyContent: 'space-between',
    alignItems: 'center', marginBottom: '16px'
  },
  downloadBtn: {
    background: 'rgba(63,200,122,0.1)', border: '1px solid rgba(63,200,122,0.2)',
    color: '#3FC87A', padding: '8px 16px', borderRadius: '8px',
    fontSize: '13px', fontWeight: '600'
  },
  emptyOutput: {
    flex: 1, display: 'flex', flexDirection: 'column',
    alignItems: 'center', justifyContent: 'center',
    padding: '40px 20px', textAlign: 'center'
  },
  emptyText: { color: '#E8E8EE', fontSize: '16px', fontWeight: '600', marginBottom: '6px' },
  emptySub: { color: '#888898', fontSize: '13px' },
  letterText: {
    color: '#b4b4c4', fontSize: '13px', lineHeight: '1.8',
    whiteSpace: 'pre-wrap', fontFamily: 'inherit',
    overflowY: 'auto', maxHeight: '500px'
  }
}

export default QuickComplaint